---
channel: edge
addons:
  grpc-bridge:
    repository: moonen-home-automation/grpc-bridge
    target: grpc-bridge
    image: ghcr.io/moonen-home-automation/grpc-bridge/{arch}
  minio:
    repository: moonen-home-automation/addon-minio
    target: addon-minio
    image: ghcr.io/moonen-home-automation/addon-minio/{arch}
