name: FortiGate BPR Streaming script
version: '4637953'
slug: fortigate-pbr-streaming
description: Script for dynamically updating Policy-based-routing policies on a FortiGate
url: https://github.com/moonen-home-automation/addon-fortigate-pbr-streaming
codenotary: rick@moonen.network
startup: services
arch:
- amd64
init: false
options:
  fortigate_api_token: ''
  fortigate_ip: 192.168.1.99
  fortigate_port: '443'
  fortigate_vdom: root
  vpn_interface: ''
  policy_number: 1
schema:
  fortigate_api_token: password
  fortigate_ip: str
  fortigate_port: int
  fortigate_vdom: str
  vpn_interface: str
  policy_number: int
image: ghcr.io/moonen-home-automation/fortigate-pbr-streaming/{arch}
