name: MinIO
version: 63670d1
slug: minio
description: High Performance Object Storage that is Open Source and Amazon S3 compatible
url: https://github.com/moonen-home-automation/addon-minio
codenotary: rick@moonen.network
ingress: true
ingress_port: 9001
ingress_stream: true
panel_icon: mdi:database
startup: services
arch:
- amd64
init: false
ports:
  9000/tcp: 9000
  9001/tcp: 9001
ports_description:
  9000/tcp: API
  9001/tcp: WebUI
options:
  user: root
  password: password
  envvars: []
schema:
  user: str
  password: password
  envvars:
  - name: match(^MINIO_([A-Z0-9_])+$)
    value: str
image: ghcr.io/moonen-home-automation/minio/{arch}
