---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '34 5 * * *'
  workflow_dispatch:

jobs:
  workflows:
    uses: moonen-home-automation/workflows/.github/workflows/labels.yaml@main
