---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  workflows:
    uses: moonen-home-automation/workflows/.github/workflows/stale.yaml@main
